pipeline {
    agent any
    tools {
        terraform 'terraform-11'
    }
    parameters {
        string(name: 'WORKSPACE', defaultValue: 'development', description:'setting up workspace for terraform')
    }
    environment {
        TF_HOME = tool('terraform-11')
        TP_LOG = "WARN"
        PATH = "$TF_HOME:$PATH"
        ACCESS_KEY = credentials('AWS_ACCESS_KEY_ID')
        SECRET_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }
    stages {
            stage('Git checkout'){
                git branch: 'main', credentialsId: '87be191b-d1f1-43d8-b679-653249159a46', url: 'https://github.com/Deepu206/terraform-pipelines.git'
            }
            stage('TerraformInit'){
                     steps {
                        dir('ec2_pipeline'){
                          script{ 
                             withAWS(roleAccount:'171934273463', role:'terraform-jenkin-role', useNode: true) {
                             sh 'terraform init -no-color'
                          }
                  }   
                }
            }
           }

        stage('TerraformFormat'){
            steps {
                dir('ec2_pipeline'){
                    sh "terraform fmt -list=true -write=false -diff=true -check=true"
                }
            }
        }

        stage('TerraformValidate'){
            steps {
                dir('ec2_pipeline'){
                    sh "terraform validate"
                }
            }
        }

        stage('TerraformPlan'){
            steps {
                dir('ec2_pipeline'){
                    script{ 
                             withAWS(roleAccount:'171934273463', role:'terraform-jenkin-role', useNode: true) {
                             sh 'terraform plan -no-color -out=plan.out'
                          }
                    
                }
            }
        }
        
        stage('TerraformApply'){
            steps {
                dir('ec2_pipeline'){
                   script{ 
                             withAWS(roleAccount:'171934273463', role:'terraform-jenkin-role', useNode: true) {
                             sh 'terraform apply -no-color -auto-approve plan.out'
                             sh "terraform output"   

                          } 
                }
            }
         }
        
       }      
  }

 
